//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelCalifornia.Backend.Shared.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationCodes {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationCodes() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HotelCalifornia.Backend.Shared.Resources.ValidationCodes", typeof(ValidationCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GUEST_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("GUEST_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        public static string LESS_THAN_ZERO {
            get {
                return ResourceManager.GetString("LESS_THAN_ZERO", resourceCulture);
            }
        }
        
        public static string PHONE_NUMBER_TOO_LONG {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_TOO_LONG", resourceCulture);
            }
        }
        
        public static string REQUIRED {
            get {
                return ResourceManager.GetString("REQUIRED", resourceCulture);
            }
        }
        
        public static string START_DATE_CANNOT_BE_EARLIER_THAN_TODAY {
            get {
                return ResourceManager.GetString("START_DATE_CANNOT_BE_EARLIER_THAN_TODAY", resourceCulture);
            }
        }
        
        public static string END_DATE_CANNOT_BE_EARLIER_THAN_TODAY {
            get {
                return ResourceManager.GetString("END_DATE_CANNOT_BE_EARLIER_THAN_TODAY", resourceCulture);
            }
        }
        
        public static string END_DATE_CANNOT_BE_EARLIER_THAN_STAR_DATE {
            get {
                return ResourceManager.GetString("END_DATE_CANNOT_BE_EARLIER_THAN_STAR_DATE", resourceCulture);
            }
        }
        
        public static string START_DATE_AND_END_DATE_CANNOT_BE_SAME {
            get {
                return ResourceManager.GetString("START_DATE_AND_END_DATE_CANNOT_BE_SAME", resourceCulture);
            }
        }
    }
}
